---
title: Stackbit Fresh Theme
baseurl: "/"
permalink: "/:title/"
layout_style: overflow
palette: blue
header:
  title: Freshy Technologies
  tagline: Globally, Easily at home
  profile_img: "/images/5225c33d-cff4-4977-884b-dcc64e814983_200x200.png"
  bg: dark
  has_nav: true
  has_social: true
footer:
  content: "&copy; All rights reserved."
  links:
  - text: Made with Stackbit
    url: https://www.stackbit.com
    new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
